twig:
    globals:
        opinions: '@App\Service\GlobalsGenerator'
    default_path: '%kernel.project_dir%/templates'
    exception_controller: null
    strict_variables: '%kernel.debug%'
    form_themes: [
        'bootstrap_4_layout.html.twig'
    ]